FROM python:3.9-slim

WORKDIR /app

COPY app.py requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 2607

CMD ["streamlit", "run", "app.py", "--server.port=2607", "--server.address=0.0.0.0"]
