name: MLOps CI Workflow
on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all jobs'
        required: true
        type: boolean
        default: true
      run_data_processing:
        description: 'Run data processing'
        required: true
        type: boolean
        default: false
      run_model_training:
        description: 'Run model training'
        required: true
        type: boolean
        default: false
      run_build_and_publish:
        description: 'Run build and publish'
        required: true
        type: boolean
        default: false

jobs:
  data_processing:
    if: ${{ inputs.run_all || inputs.run_data_processing || inputs.run_model_training || inputs.run_build_and_publish }}
    uses: './.github/workflows/mlops-data-processing-template.yml'
  
  model-training:
    if: ${{ inputs.run_all || inputs.run_model_training || inputs.run_build_and_publish }}
    uses: './.github/workflows/mlops-model-training-template.yml'
    needs: data_processing

  build-and-publish:
    if: ${{ inputs.run_all || inputs.run_build_and_publish }}
    uses: './.github/workflows/mlops-build-and-publish-template.yml'
    needs: model-training
    